version: 0.2

phases: 
    pre_build:
        commands:
            - echo "Pre-build phase"
            - pwd
            - ls -la
    build:
        commands:
            - echo "Build phase"
            - if [ -f index.html ]; then grep "Congratulations" index.html || echo "Pattern not found"; fi
    post_build:
        commands:
            - echo "Post-build phase"
            - echo "Hello MernOps"

artifacts:
    files:
        - scripts/install_dependencies
        - scripts/start_server
        - scripts/stop_server
        - index.html
        - appspec.yml
    discard-paths: yes